theme: just-the-docs
#theme: jekyll-theme-minimal
title: "CB2442"
description: "Here we store material for the Data Analysis part of the CB2442, Bioinformatics course."
logo: assets/image/kth_logo.png

plugins:
  - jekyll-relative-links
  - jekyll-jupyter-notebook
relative_links:
  enabled: true
  collections: true
