# Remote Setting
baseurl: "/cb2442"
remote_theme: pages-themes/dinky@v0.2.0
title: "CB2442"
description: "Here we store material for the course CB2442, Bioinformatics."
logo: assets/images/kth_logo.png

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-jupyter-notebook
relative_links:
  enabled: true
  collections: true
